# Carbon_Prediction_Time_Series_Analysis

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pandas_datareader import wb

In [2]:
# URL for data site
# https://databank.worldbank.org/source/world-development-indicators

In [3]:
code = 'EN.CO2.BLDG.ZS'
regions = ['BRA', 'IND', 'CHN', 'ZAF', 'USA', 'GBR', 'WLD', 'EUU']

In [4]:
df_indicator = wb.download(
    country=regions,
    indicator=code, 
    start=1971,
    end=2014
)

C:\Users\South\AppData\Roaming\Python\Python311\site-packages\pandas_datareader\wb.py:592: UserWarning: Non-standard ISO country codes: EUU, WLD
  warnings.warn(

In [5]:
# df_indicator['Country'].unique()

In [6]:
df_indicator.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 352 entries, ('Brazil', '2014') to ('South Africa', '1971')
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EN.CO2.BLDG.ZS  352 non-null    float64
dtypes: float64(1)
memory usage: 5.3+ KB

In [7]:
df_indicator

                   EN.CO2.BLDG.ZS
country      year
Brazil       2014        4.289736
             2013        4.508896
             2012        4.746116
             2011        5.159270
             2010        5.346396
...                           ...
South Africa 1975        6.572400
             1974        6.815974
             1973        6.949115
             1972        7.742371
             1971        7.925393

[352 rows x 1 columns]

In [8]:
df_indicator.to_excel('indicator_world_bank.xlsx')

In [9]:
pd.set_option("display.max_rows", None)

In [10]:
df_indicator

                     EN.CO2.BLDG.ZS
country        year
Brazil         2014        4.289736
               2013        4.508896
               2012        4.746116
               2011        5.159270
               2010        5.346396
               2009        6.042296
               2008        5.728822
               2007        6.021721
               2006        6.104512
               2005        6.177134
               2004        6.369242
               2003        6.573187
               2002        7.184062
               2001        7.230568
               2000        7.320995
               1999        7.695609
               1998        7.568926
               1997        7.635852
               1996        8.034153
               1995        8.629018
               1994        8.940114
               1993        8.748152
               1992        8.814062
               1991        8.735680
               1990        8.938942
               1989        8.538303
               1988        8.511921
               1987        7.800390
               1986        7.491558
               1985        7.913945
               1984        7.689197
               1983        8.026440
               1982        7.438704
               1981        6.784000
               1980        6.153479
               1979        5.783516
               1978        5.635035
               1977        5.670138
               1976        5.767214
               1975        5.927298
               1974        6.133508
               1973        6.568496
               1972        7.056473
               1971        7.044025
China          2014        5.358338
               2013        5.306225
               2012        5.302652
               2011        5.205434
               2010        5.401937
               2009        5.573417
               2008        5.798459
               2007        6.156229
               2006        6.495481
               2005        6.819781
               2004        7.462184
               2003        7.611126
               2002        8.108541
               2001        8.563851
               2000        8.881148
               1999        9.813584
               1998        9.256623
               1997       11.471135
               1996       10.283800
               1995       12.216496
               1994       12.670941
               1993       14.310941
               1992       15.160175
               1991       16.898704
               1990       17.911886
               1989       18.052685
               1988       18.860396
               1987       18.922522
               1986       19.392149
               1985       20.021037
               1984       18.559930
               1983       18.872562
               1982       18.794264
               1981       18.891944
               1980       18.139023
               1979       19.026029
               1978       18.922859
               1977       19.983016
               1976       19.931858
               1975       20.465564
               1974       20.318703
               1973       20.831115
               1972       21.329853
               1971       21.596575
European Union 2014       15.459913
               2013       17.060117
               2012       16.344142
               2011       15.673458
               2010       17.275371
               2009       16.880886
               2008       16.024392
               2007       14.444750
               2006       16.485827
               2005       16.609216
               2004       16.525770
               2003       16.631710
               2002       16.253825
               2001       16.891597
               2000       16.064259
               1999       16.852581
               1998       16.842029
               1997       17.164758
               1996       17.994964
               1995       16.999967
               1994       16.963227
               1993       18.091799
               1992       17.635793
               1991       18.337554
               1990       17.208227
               1989       17.777301
               1988       19.277612
               1987       20.099663
               1986       20.319986
               1985       19.945683
               1984       18.949995
               1983       17.555994
               1982       18.048506
               1981       18.364368
               1980       18.604842
               1979       19.616910
               1978       19.879768
               1977       19.668188
               1976       20.164812
               1975       20.728440
               1974       20.240601
               1973       21.894976
               1972       22.129084
               1971       21.950546
United Kingdom 2014       19.061397
               2013       20.827589
               2012       20.131135
               2011       19.065864
               2010       21.763386
               2009       20.262562
               2008       19.615369
               2007       17.425913
               2006       17.852515
               2005       18.682105
               2004       19.412008
               2003       18.791568
               2002       19.131338
               2001       19.615715
               2000       19.550993
               1999       19.903614
               1998       20.556720
               1997       20.362663
               1996       21.072553
               1995       19.728235
               1994       20.144903
               1993       19.524976
               1992       18.505325
               1991       18.568980
               1990       17.461795
               1989       17.501964
               1988       18.346940
               1987       19.089099
               1986       19.970250
               1985       20.044531
               1984       19.114797
               1983       19.276227
               1982       18.915224
               1981       18.749887
               1980       18.444117
               1979       18.140961
               1978       17.977528
               1977       18.214177
               1976       17.870337
               1975       17.964301
               1974       18.435426
               1973       17.421817
               1972       18.141505
               1971       17.230274
India          2014        5.490006
               2013        5.704307
               2012        5.701490
               2011        6.173230
               2010        6.208523
               2009        6.272677
               2008        6.596951
               2007        6.926106
               2006        7.464892
               2005        7.806740
               2004        8.029992
               2003        8.450926
               2002        8.393903
               2001        8.312896
               2000        8.569920
               1999        8.981337
               1998        9.203234
               1997        9.682830
               1996        9.399644
               1995        9.567884
               1994        9.898968
               1993        9.674980
               1992        9.981702
               1991       10.502491
               1990       10.750174
               1989       10.385573
               1988       10.832227
               1987       10.331186
               1986       10.513108
               1985       11.790532
               1984       12.936693
               1983       12.349177
               1982       12.277563
               1981       12.998056
               1980       12.617357
               1979       13.698245
               1978       13.587028
               1977       12.602554
               1976       12.336263
               1975       12.209276
               1974       12.503688
               1973       14.183907
               1972       14.035274
               1971       15.087564
United States  2014       11.011918
               2013       10.679440
               2012        9.712099
               2011       10.230125
               2010       10.190292
               2009       10.765703
               2008       10.089048
               2007        9.652542
               2006        9.236012
               2005       10.026884
               2004       10.374837
               2003       10.795368
               2002       10.525574
               2001       10.374585
               2000       10.614358
               1999       10.429247
               1998       10.127646
               1997       11.116011
               1996       11.782331
               1995       11.430109
               1994       11.459922
               1993       11.821319
               1992       11.678485
               1991       11.647482
               1990       11.354621
               1989       12.341935
               1988       12.478183
               1987       12.291143
               1986       12.482161
               1985       12.713879
               1984       13.308658
               1983       13.367894
               1982       13.757522
               1981       13.182341
               1980       13.948417
               1979       14.846802
               1978       16.105992
               1977       16.128702
               1976       17.264680
               1975       17.031575
               1974       16.687413
               1973       17.048219
               1972       18.390586
               1971       19.061400
World          2014        8.595320
               2013        8.804332
               2012        8.632350
               2011        8.805714
               2010        9.204829
               2009        9.615836
               2008        9.636771
               2007        9.471573
               2006        9.862386
               2005       10.318906
               2004       10.661540
               2003       10.976542
               2002       11.088939
               2001       11.303043
               2000       11.376438
               1999       11.733563
               1998       11.461488
               1997       12.239945
               1996       12.495706
               1995       12.441500
               1994       12.408827
               1993       12.856742
               1992       12.637935
               1991       13.118099
               1990       13.062378
               1989       14.118404
               1988       14.706352
               1987       14.925878
               1986       15.237551
               1985       15.348561
               1984       15.123734
               1983       14.811580
               1982       15.043773
               1981       14.848475
               1980       15.118228
               1979       15.885459
               1978       16.480944
               1977       16.512286
               1976       17.137039
               1975       17.173455
               1974       16.947899
               1973       17.565715
               1972       18.432397
               1971       18.615556
South Africa   2014        5.469054
               2013        5.591515
               2012        5.553239
               2011        4.123685
               2010        3.412499
               2009        7.821341
               2008        7.653411
               2007        7.648682
               2006        6.463258
               2005        5.780440
               2004        5.300589
               2003        5.048098
               2002        4.825286
               2001        4.047777
               2000        3.276176
               1999        3.518559
               1998        3.668185
               1997        3.964510
               1996        4.054455
               1995        4.743022
               1994        5.633916
               1993        6.140351
               1992        4.983431
               1991        4.948048
               1990        4.642769
               1989        4.408225
               1988        3.855380
               1987        3.468110
               1986        3.590795
               1985        4.292827
               1984        4.343288
               1983        3.577267
               1982        3.643013
               1981        3.923803
               1980        4.856512
               1979        6.058166
               1978        6.764253
               1977        5.527939
               1976        6.429296
               1975        6.572400
               1974        6.815974
               1973        6.949115
               1972        7.742371
               1971        7.925393

In [11]:
df_indicator.isnull().sum()

EN.CO2.BLDG.ZS    0
dtype: int64

In [12]:
df_indicator = df_indicator.reset_index()

In [13]:
df_indicator.head()

  country  year  EN.CO2.BLDG.ZS
0  Brazil  2014        4.289736
1  Brazil  2013        4.508896
2  Brazil  2012        4.746116
3  Brazil  2011        5.159270
4  Brazil  2010        5.346396

In [14]:
type(df_indicator['year'][0])

str

In [15]:
df_indicator['year'] = df_indicator['year'].astype(int)
type(df_indicator['year'][0])

numpy.int32

In [16]:
df_indicator.set_index('year', inplace=True)
df_indicator.head()

     country  EN.CO2.BLDG.ZS
year
2014  Brazil        4.289736
2013  Brazil        4.508896
2012  Brazil        4.746116
2011  Brazil        5.159270
2010  Brazil        5.346396

In [17]:
df_indicator = df_indicator.sort_index()
df_indicator.head()

             country  EN.CO2.BLDG.ZS
year
1971  United Kingdom       17.230274
1971           World       18.615556
1971   United States       19.061400
1971           India       15.087564
1971  European Union       21.950546

In [18]:
df_indicator.columns = ["country", "Indicator"]
df_indicator.head()

             country  Indicator
year
1971  United Kingdom  17.230274
1971           World  18.615556
1971   United States  19.061400
1971           India  15.087564
1971  European Union  21.950546

In [19]:
df_indicator.head(10)

             country  Indicator
year
1971  United Kingdom  17.230274
1971           World  18.615556
1971   United States  19.061400
1971           India  15.087564
1971  European Union  21.950546
1971           China  21.596575
1971          Brazil   7.044025
1971    South Africa   7.925393
1972   United States  18.390586
1972          Brazil   7.056473

In [20]:
# df_indicator.info

In [21]:
df_indicator = pd.pivot_table(data=df_indicator, columns='country', 
                              index='year', values='Indicator')

In [22]:
df_indicator

country,Brazil,China,European Union,India,South Africa,United Kingdom,United States,World
year,,,,,,,,
1971,7.044025,21.596575,21.950546,15.087564,7.925393,17.230274,19.061400,18.615556
1972,7.056473,21.329853,22.129084,14.035274,7.742371,18.141505,18.390586,18.432397
1973,6.568496,20.831115,21.894976,14.183907,6.949115,17.421817,17.048219,17.565715
1974,6.133508,20.318703,20.240601,12.503688,6.815974,18.435426,16.687413,16.947899
1975,5.927298,20.465564,20.728440,12.209276,6.572400,17.964301,17.031575,17.173455
1976,5.767214,19.931858,20.164812,12.336263,6.429296,17.870337,17.264680,17.137039
1977,5.670138,19.983016,19.668188,12.602554,5.527939,18.214177,16.128702,16.512286
1978,5.635035,18.922859,19.879768,13.587028,6.764253,17.977528,16.105992,16.480944
1979,5.783516,19.026029,19.616910,13.698245,6.058166,18.140961,14.846802,15.885459
1980,6.153479,18.139023,18.604842,12.617357,4.856512,18.444117,13.948417,15.118228
1981,6.784000,18.891944,18.364368,12.998056,3.923803,18.749887,13.182341,14.848475
1982,7.438704,18.794264,18.048506,12.277563,3.643013,18.915224,13.757522,15.043773
1983,8.026440,18.872562,17.555994,12.349177,3.577267,19.276227,13.367894,14.811580
1984,7.689197,18.559930,18.949995,12.936693,4.343288,19.114797,13.308658,15.123734
1985,7.913945,20.021037,19.945683,11.790532,4.292827,20.044531,12.713879,15.348561
1986,7.491558,19.392149,20.319986,10.513108,3.590795,19.970250,12.482161,15.237551
1987,7.800390,18.922522,20.099663,10.331186,3.468110,19.089099,12.291143,14.925878
1988,8.511921,18.860396,19.277612,10.832227,3.855380,18.346940,12.478183,14.706352
1989,8.538303,18.052685,17.777301,10.385573,4.408225,17.501964,12.341935,14.118404
1990,8.938942,17.911886,17.208227,10.750174,4.642769,17.461795,11.354621,13.062378
1991,8.735680,16.898704,18.337554,10.502491,4.948048,18.568980,11.647482,13.118099
1992,8.814062,15.160175,17.635793,9.981702,4.983431,18.505325,11.678485,12.637935
1993,8.748152,14.310941,18.091799,9.674980,6.140351,19.524976,11.821319,12.856742
1994,8.940114,12.670941,16.963227,9.898968,5.633916,20.144903,11.459922,12.408827
1995,8.629018,12.216496,16.999967,9.567884,4.743022,19.728235,11.430109,12.441500
1996,8.034153,10.283800,17.994964,9.399644,4.054455,21.072553,11.782331,12.495706
1997,7.635852,11.471135,17.164758,9.682830,3.964510,20.362663,11.116011,12.239945
1998,7.568926,9.256623,16.842029,9.203234,3.668185,20.556720,10.127646,11.461488
1999,7.695609,9.813584,16.852581,8.981337,3.518559,19.903614,10.429247,11.733563
2000,7.320995,8.881148,16.064259,8.569920,3.276176,19.550993,10.614358,11.376438
2001,7.230568,8.563851,16.891597,8.312896,4.047777,19.615715,10.374585,11.303043
2002,7.184062,8.108541,16.253825,8.393903,4.825286,19.131338,10.525574,11.088939
2003,6.573187,7.611126,16.631710,8.450926,5.048098,18.791568,10.795368,10.976542
2004,6.369242,7.462184,16.525770,8.029992,5.300589,19.412008,10.374837,10.661540
2005,6.177134,6.819781,16.609216,7.806740,5.780440,18.682105,10.026884,10.318906
2006,6.104512,6.495481,16.485827,7.464892,6.463258,17.852515,9.236012,9.862386
2007,6.021721,6.156229,14.444750,6.926106,7.648682,17.425913,9.652542,9.471573
2008,5.728822,5.798459,16.024392,6.596951,7.653411,19.615369,10.089048,9.636771
2009,6.042296,5.573417,16.880886,6.272677,7.821341,20.262562,10.765703,9.615836
2010,5.346396,5.401937,17.275371,6.208523,3.412499,21.763386,10.190292,9.204829
2011,5.159270,5.205434,15.673458,6.173230,4.123685,19.065864,10.230125,8.805714
2012,4.746116,5.302652,16.344142,5.701490,5.553239,20.131135,9.712099,8.632350
2013,4.508896,5.306225,17.060117,5.704307,5.591515,20.827589,10.679440,8.804332
2014,4.289736,5.358338,15.459913,5.490006,5.469054,19.061397,11.011918,8.595320

In [26]:
regions

['BRA', 'IND', 'CHN', 'ZAF', 'USA', 'GBR', 'WLD', 'EUU']

In [27]:
df_indicator.columns = regions[0], regions[2], regions[7], regions[1], regions[3], regions[5], regions[4], regions[6]

In [28]:
df_indicator

,BRA,CHN,EUU,IND,ZAF,GBR,USA,WLD
year,,,,,,,,
1971,7.044025,21.596575,21.950546,15.087564,7.925393,17.230274,19.061400,18.615556
1972,7.056473,21.329853,22.129084,14.035274,7.742371,18.141505,18.390586,18.432397
1973,6.568496,20.831115,21.894976,14.183907,6.949115,17.421817,17.048219,17.565715
1974,6.133508,20.318703,20.240601,12.503688,6.815974,18.435426,16.687413,16.947899
1975,5.927298,20.465564,20.728440,12.209276,6.572400,17.964301,17.031575,17.173455
1976,5.767214,19.931858,20.164812,12.336263,6.429296,17.870337,17.264680,17.137039
1977,5.670138,19.983016,19.668188,12.602554,5.527939,18.214177,16.128702,16.512286
1978,5.635035,18.922859,19.879768,13.587028,6.764253,17.977528,16.105992,16.480944
1979,5.783516,19.026029,19.616910,13.698245,6.058166,18.140961,14.846802,15.885459
1980,6.153479,18.139023,18.604842,12.617357,4.856512,18.444117,13.948417,15.118228
1981,6.784000,18.891944,18.364368,12.998056,3.923803,18.749887,13.182341,14.848475
1982,7.438704,18.794264,18.048506,12.277563,3.643013,18.915224,13.757522,15.043773
1983,8.026440,18.872562,17.555994,12.349177,3.577267,19.276227,13.367894,14.811580
1984,7.689197,18.559930,18.949995,12.936693,4.343288,19.114797,13.308658,15.123734
1985,7.913945,20.021037,19.945683,11.790532,4.292827,20.044531,12.713879,15.348561
1986,7.491558,19.392149,20.319986,10.513108,3.590795,19.970250,12.482161,15.237551
1987,7.800390,18.922522,20.099663,10.331186,3.468110,19.089099,12.291143,14.925878
1988,8.511921,18.860396,19.277612,10.832227,3.855380,18.346940,12.478183,14.706352
1989,8.538303,18.052685,17.777301,10.385573,4.408225,17.501964,12.341935,14.118404
1990,8.938942,17.911886,17.208227,10.750174,4.642769,17.461795,11.354621,13.062378
1991,8.735680,16.898704,18.337554,10.502491,4.948048,18.568980,11.647482,13.118099
1992,8.814062,15.160175,17.635793,9.981702,4.983431,18.505325,11.678485,12.637935
1993,8.748152,14.310941,18.091799,9.674980,6.140351,19.524976,11.821319,12.856742
1994,8.940114,12.670941,16.963227,9.898968,5.633916,20.144903,11.459922,12.408827
1995,8.629018,12.216496,16.999967,9.567884,4.743022,19.728235,11.430109,12.441500
1996,8.034153,10.283800,17.994964,9.399644,4.054455,21.072553,11.782331,12.495706
1997,7.635852,11.471135,17.164758,9.682830,3.964510,20.362663,11.116011,12.239945
1998,7.568926,9.256623,16.842029,9.203234,3.668185,20.556720,10.127646,11.461488
1999,7.695609,9.813584,16.852581,8.981337,3.518559,19.903614,10.429247,11.733563
2000,7.320995,8.881148,16.064259,8.569920,3.276176,19.550993,10.614358,11.376438
2001,7.230568,8.563851,16.891597,8.312896,4.047777,19.615715,10.374585,11.303043
2002,7.184062,8.108541,16.253825,8.393903,4.825286,19.131338,10.525574,11.088939
2003,6.573187,7.611126,16.631710,8.450926,5.048098,18.791568,10.795368,10.976542
2004,6.369242,7.462184,16.525770,8.029992,5.300589,19.412008,10.374837,10.661540
2005,6.177134,6.819781,16.609216,7.806740,5.780440,18.682105,10.026884,10.318906
2006,6.104512,6.495481,16.485827,7.464892,6.463258,17.852515,9.236012,9.862386
2007,6.021721,6.156229,14.444750,6.926106,7.648682,17.425913,9.652542,9.471573
2008,5.728822,5.798459,16.024392,6.596951,7.653411,19.615369,10.089048,9.636771
2009,6.042296,5.573417,16.880886,6.272677,7.821341,20.262562,10.765703,9.615836
2010,5.346396,5.401937,17.275371,6.208523,3.412499,21.763386,10.190292,9.204829
2011,5.159270,5.205434,15.673458,6.173230,4.123685,19.065864,10.230125,8.805714
2012,4.746116,5.302652,16.344142,5.701490,5.553239,20.131135,9.712099,8.632350
2013,4.508896,5.306225,17.060117,5.704307,5.591515,20.827589,10.679440,8.804332
2014,4.289736,5.358338,15.459913,5.490006,5.469054,19.061397,11.011918,8.595320